### ISSUE TITLE
type3E.randomwrite_bitunitsについて

### ISSUE THREAD

**Issue by tyaro** [senrust/pymcprotocol#1]
835行目の_encode_devicevalueへの引数でbit_deviceであるべきところが
bit_devicesになっているようです。

```py
            request_data += self._encode_devicevalue(value, bit_devices, mode="byte")
```

**Comment by senrust** [comment]
Thank you very much for reporting.
Fixed type3E.randomwrite_bitunits and released new version 0.2.7.

ご指摘ありがとうございました.
修正し新バージョンをリリースしました.

(差し支えなければですが, tyaroさんのPLCでREADME.mdにある一通りの関数を実行していただけないでしょうか?
Version 0.25以降私の手元にPLCがなく, 仕様書を読んで実装を行っています.
実機で動作するのかテストできない状況です. 
PLCのタイプは問いません. ご協力可能でしたらどうぞよろしくお願いいたします.)

**Comment by tyaro** [comment]
さっそく反映ありがとうございました

Q13UDV+QJ71E71-100でReadmeの関数確認しました。

Readmeの例でランダム書込の`word_value` を`word_values` にしたぐらいで他は動作大丈夫です。

**NG**
```py
pymc3e.randomwrite(word_devices=["D1000", "D1002"], word_value=[1000, 2000], 
                   dword_devices=["D1004"], dword_values=[655362])
```

**OK**
```py
pymc3e.randomwrite(word_devices=["D1000", "D1002"], word_values=[1000, 2000], 
                   dword_devices=["D1004"], dword_values=[655362])
```
実機で行うと通信環境によりますが、BlockReadで多めのデバイスを読み出す時など
バッファを多めにとっても応答伝文が分割されて送られてくるので、応答を結合する必要があります。
※ワード：readsize=読込点数*2
※ビット：readsize=読込点数
上記はバイナリ時


```py
    def _recv(self,readsize):
        recv_data = bytes()
        datasize = readsize  + 11 
        if len(recv_data) < datasize:
            while True:
                recv_data += self._sock.recv(self._SOCKBUFSIZE)
                if len(recv_data) == datasize:
                    break
        return recv_data
```
MCプロトコルは終了コードが0x00なので、応答伝文長が溢れたときのエラー処理も必要かもしれません。

**Comment by senrust** [comment]
この度はテストへのご協力誠にありがとうございました。
心より御礼申し上げます。

READMEを修正いたしました。

分割受信の件、知りませんでした。本当にありがとうございます。
コード例まで頂き恐縮です。
よろしければtyaroさんをContributerに招待させて頂きたいのですがよろしいでしょうか?

```python
    def _recv(self,readsize):
        recv_data = bytes()
        datasize = readsize  + 11 
        if len(recv_data) < datasize:
            while True:
                recv_data += self._sock.recv(self._SOCKBUFSIZE)
                if len(recv_data) == datasize:
                    break
        return recv_data
```
については, 受信ヘッダーサイズをtype3eとtype4e, asciiとバイナリに応じて変えて,
コマンドごとに適切なサイズを与えるだけで良さそうですね。
developブランチにこちらをpushしていただければ幸いです。

> MCプロトコルは終了コードが0x00なので、応答伝文長が溢れたときのエラー処理も必要かもしれません

ソケットバッファサイズは現在4096バイト用意しています。
PLCがこのサイズ以上のデータを一度に送ってくる可能性を考え、拡張が必要という認識でよろしいでしょうか?

PLC用ライブラリなのにPLCなしで実装という意味不明な状況に苦慮していたので、
本当に助かりました。
改めて御礼申し上げます。

**Comment by tyaro** [comment]
Contributerの件問題ないですが、Gitリポジトリの使い方まだ慣れていないので少し練習しておきます。
応答伝文の溢れですが、例えば960ワードをブロック読出ししたときの受信データ長はヘッダ部と終了コードも合わせて
1931ワードになりますが、_socket.recvで受けとるデータが1400バイトと531バイトに別れて受信する場合があります。
上のコードでは先に1400バイト来たときに次は531バイトもしくは531バイトが更に分割されて、最終的に1931バイト丁度になるという前提で組んでいますが、実際には外的要因などで、バイト数が想定と違うことも起きうるかと思います。
その場合ループが終わらないのでアラームを出す必要があるかなと思います。
