### ISSUE TITLE
does it support FX5U cpu?

### ISSUE THREAD

**Issue by pankajmowito** [senrust/pymcprotocol#10]
I am trying to connect with FX5U-32MT/ESS PLC. but I am unable to connect with it. does pymcprotocol support this plc model?

**Comment by senrust** [comment]
Yes. You can use SLMP communication, equivalent to  mcprotocol type 3E.
Please set IP address and open a TCP/IP port  for SLMP.

**Comment by pankajmowito** [comment]
hi @senrust, thanks for the reply. I have setup the TCP/IP port for the SLMP and I am using: 
```pymc3e = pymcprotocol.Type3E(plctype="QnA")``` 

but still I am unable to connect to PLC.

error:
```
pymc3e.connect("192.168.3.250", 502)
File "C:\Users\panka\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pymcprotocol\type3e.py", line 124, in connect self._sock.connect((ip, port))
TimeoutError: timed out 
```

can you give some suggestion.

I have followed this for setting up the SLMP in plc : [youtube](https://youtu.be/RBRx3XZX2z8?t=1406)

**Comment by senrust** [comment]
Ok. "plctype="QnA" is correct.
Did you restart your PLC after setting?
Does ping command reach?

**Comment by pankajmowito** [comment]
yes I have restarted the plc, still it is not working. what is ping command?

**Comment by senrust** [comment]
Please check!
https://www.howtogeek.com/355664/how-to-use-ping-to-test-your-network/

**Comment by pankajmowito** [comment]
is it cli command,  ping? ya its not working. 
what could be the issue?

**Comment by pankajmowito** [comment]
should not be the firewall , because I have also tried it on ubuntu.

**Comment by senrust** [comment]
OK. Can you show your IP address and Subnet mask.
I think that your PLC's IP address is wrong. 
You need to assign right IP address, same Subnet mask, to your PLC.
For example, If your PC's IP address is 192.168.1.100 and Subnet mask is 255.255.255.0,
your PLC's IP address should be 192.168.1.1 ~ 192.168.1.244 and not conflicted to other devices.

**Comment by pankajmowito** [comment]
thanks a lot, I am able to connect to the PLC.

**Comment by pankajmowito** [comment]
thanks a lot, I am able to connect to the PLC. (although I am unable to send string value to PLC registers)
so my ip was 192.168.1.21
subnet mast : 255.255.255.0
and gateway: 192.168.1.1

I set the PLC ip as : 192.168.1.130 (earlier it was 192.168.3.250 (default one), that's why it was not working)
subnet and gateway is set as mentioned above. 

thanks again.
