### ISSUE TITLE
Library For FX Series over the MELSEC protocol 

### ISSUE THREAD

**Issue by Rahul14189** [senrust/pymcprotocol#16]
Can you suggest any library for FX series over the MELSEC protocol ?

**Comment by senrust** [comment]
Unfortunately, FX series does not support MCProtocol Type 3E. So You cannot use pymcprotocol for FX series.
FX series supports Type 1C maybe.
How about implement this?
I think it's not tough.

**Comment by Rahul14189** [comment]
Sounds good, but i think it supports Type 1E probably. Let me check.
