### ISSUE TITLE
I think pymcprotocol needs keep-alive option.

### ISSUE THREAD

**Issue by Hiroki-H1974** [senrust/pymcprotocol#18]
type.3e.py
+124 self._sock.setsockopt(socket.SOL_SOCKET, socket.SO_KEEPALIVE, 1)

I have experienced on Windows & PLC, WinError 10055 occured
when contiguous long-term connection (more than 2 weeks, contiguous running)
In this python program, pymc.batchread_bitunits ... and elsewhere
are called more than 10 times at a sec.

Am I wrong? I have not confirmed this trial.

**Comment by senrust** [comment]
Thank you very much for using pymcprotocol.  
WinError 10055 means too many socket is opened.  
I suppose that you create too many pymcprotocol.type3e instances at a short time before sockets created by scope-outed pymcprotocol.type3e instances are disposed and WinError 10055 occured.
Can you reuse a pymcprotocol.type3e instance?

Best regards.

**Comment by Hiroki-H1974** [comment]
I have very big mistake.

Off course, I reused one instance of .type3e.
And I executed on Windows PowerShell, 
get-nettcpconnection | where-object{$_.RemoteAddress -eq 'xxx.yyy.zzz.www'}
where xxx.yyy.zzz.www is IP address of PLC connected by .type3e.
Then, the result showed only one line.
So, pymcprotocol is very fine and flawless.

BUT, WinError 10055 occured every about 10 days.
It will be exist some bug in other point.

This python program uses another only one IP address to robot server.
And I executed the same PowerShell script above.
The result is also only one line.

I cannot understand why this error occurs...

**Comment by senrust** [comment]
Thank you for your reply.  
返信ありがとうございます。
日本の方だと思いますので、日本語にて返信いたします。  

WinError 10055は、
1. Openしているソケット数が上限に達した  
2. ソケット内のバッファ使用量が上限に達した
を意味しているようです。

率直に申し上げて、通常のpymcprotocolの使用では、このようなエラーが発生するとは考えていません。
お使いの環境のセキュリティソフト、Windowsの設定等の問題かもしれません。


暫定対処として、作成されたPythonスクリプトを編集し、ロボットとの通信の都度type3Eインスタンスを作成してみてください。
接続、コマンド実行、切断を都度繰り返せば、
必ずソケットリソースの回収がOSで実施され、
エラーを回避できるのではないかと想定しています。
(もし大量にデータ通信をされ、インスタンス化の遅延が気になるようでしたら数分おきでも問題ないと思います。)

あまりお力になれず申し訳ありませんが、どうぞよろしくお願いします。

**Comment by Hiroki-H1974** [comment]
日本語での対応ありがとうございます。

先のレスでも述べたとおり、ソケットはあくまでも１つなのにWinError10055が
発生するのは、あとはWindowsかPythonインタープリタにメモリーリーク系の
バグがあるのではと考えています。

FA系で自動車生産ラインでの使用なので、最悪は週１でPCを再起動することを
業務にしてもらうことで不具合は回避できますが、原因が分からないままなのは
気持ち悪いです。
ただ、pymcprotocol は問題ないことが分かったので、このIssueはクローズと
させてください。
