### ISSUE TITLE
Understanding of pymcprotocol

### ISSUE THREAD

**Issue by mes20a42** [senrust/pymcprotocol#2]
Hi there, thanks for your effort in making this package. I would like to understand the following questions
1) Is it possible to read and write data via ethernet module of the PLC ?
2) Can I control the reading occurrence as from what I understood it seems like the function (batchread) is continuously reading from the PLC

Thanks in advance
Eason

**Comment by senrust** [comment]
Thank you for using pymcprotocol.

1. Yes. You should use setaccessopt method.
    You can change protocol header. 
    https://pymcprotocol.netlify.app/_modules/pymcprotocol/type3e.html#Type3E.setaccessopt
    Please change protocol header for your network structure.

2. No.
   pymcprotocol does not support monitering condition.
  
Best Regards,
Yohei Osawa

**Comment by mes20a42** [comment]
> Thank you for using pymcprotocol.
> 
> 1. Yes. You should use setaccessopt method.
>    You can change protocol header.
>    https://pymcprotocol.netlify.app/_modules/pymcprotocol/type3e.html#Type3E.setaccessopt
>    Please change protocol header for your network structure.
> 2. No.
>    pymcprotocol does not support monitering condition.
> 
> Best Regards,
> Yohei Osawa

Hi Yohei Osawa-san,

I understand. Thanks for getting back to me

すぐる

**Comment by senrust** [comment]
I'm going to  add monitering condition in next major update.
Thank you for your suggestion!
