### ISSUE TITLE
Q-FX 5 Uシリーズは使えますか

### ISSUE THREAD

**Issue by Ahong303** [senrust/pymcprotocol#20]
こんにちは！iQ-FX 5 Uは公式の説明によると、slmpをサポートしているので、使用できるかどうか、どのように使用するかをお聞きします

**Comment by senrust** [comment]
はい使用できます。
TYPE3Eに対応しているようなので、
そのままType3Eクラスを使用してください!

2024年10月1日(火) 10:24 Ahong303 ***@***.***>:
