### ISSUE TITLE
type3E.randomwrite_bitunits 書込みデータのバイト数

### ISSUE THREAD

**Issue by chamiso** [senrust/pymcprotocol#3]
以下のコードをiQ-R CPUに対して発行すると0xC061エラーとなります。

import pymcprotocol
pymc3e = pymcprotocol.Type3E()
pymc3e = pymcprotocol.Type3E(plctype="iQ-R")
pymc3e.connect("192.168.1.2", 1025)
pymc3e.randomwrite_bitunits(bit_devices=["X0"], values=[1])

WireSharkでパケットデータを確認するとvaluesの値が1バイト値として送信されています。
サブコマンドが0003の場合、書込みデータは2バイトである必要があります。
（SLMPリファレンスマニュアル(SH-080931)　Write Random(コマンド:1402) ■セット/リセット参照）
<img width="758" alt="slmp_manual" src="https://user-images.githubusercontent.com/61182701/115508038-d61ef500-a2b7-11eb-8230-8bd08be50d03.png">

[pymcprotocolでNGとなるメッセージ]
<img width="492" alt="iqrreqng" src="https://user-images.githubusercontent.com/61182701/115508551-6826fd80-a2b8-11eb-8b4c-448c274e890f.png">

[メッセージを自作し、OKとなるメッセージ]
<img width="496" alt="iqrreqok" src="https://user-images.githubusercontent.com/61182701/115508570-6d844800-a2b8-11eb-87da-896a784fe0e2.png">

**Comment by senrust** [comment]
この度はご報告ありがとうございました。
SLMPマニュアルを確認したところ、確かに正しい送信データではありませんでした。
randomwrite_bitunitsを修正し, 0.2.8をリリースしました。

QシリーズのMCプロトコルマニュアルを参考に実装していたので、
iQ-Rシリーズのrandomwrite_bitunits時の挙動が異なる点に気が付きませんでした。

厚かましいようで恐縮ですが、
もし可能でしたらhamiso様のiQ-RシリーズでReadmeにあるコマンドを一通り実行し、
動作チェックをしていただけないでしょうか?
iQ-Rシリーズはなかなか個人の手の届く価格ではなく、
実装で対応していても実機テストができない状況に苦慮しております。

お手数ですがご検討のほど、どうぞよろしくお願いいたします。

**Comment by chamiso** [comment]
ご対応いただきありがとうございます。
こちらの環境でReadmeのコマンドをチェックいたしました。
しかしながら、以下のコードでエラーが発生します。

pymc3e.batchwrite_wordunits(headdevice="D10", values=[0, 10, 20, 30, 40])
Traceback (most recent call last):
  File "C:\Users\UserName\AppData\Local\Programs\Python\Python39\lib\site-packages\pymcprotocol\type3e.py", line 368, in _encode_value
    raise ValueError("Please input value type")
ValueError: Please input value type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\UserName\AppData\Local\Programs\Python\Python39\lib\site-packages\pymcprotocol\type3e.py", line 529, in batchwrite_wordunits
    request_data += self._encode_value(value, headdevice, isSigned=True)
  File "C:\Users\UserName\AppData\Local\Programs\Python\Python39\lib\site-packages\pymcprotocol\type3e.py", line 387, in _encode_value
    raise ValueError("Exceeeded Device value range")
ValueError: Exceeeded Device value range

ソースコードを拝見したところ、本件とは無関係の箇所が修正されています。
本件の修正であれば、以下の箇所だけで問題ないのではないでしょうか。

            #byte value for iQ-R requires 2 byte data
            if self.plctype == const.iQR_SERIES:
                request_data += self._encode_value(value, mode="short", isSigned=True)
            else:
                request_data += self._encode_value(value, mode="byte", isSigned=True)

また0.2.8からPython 3.4, 3.5のサポートが打ち切られており、困っております。
申し訳ございませんが、せめて3.5以降をサポートいただけないでしょうか。

お手数ですが、ご検討のほどよろしくお願いします。

**Comment by chamiso** [comment]
修正方法を見直しました。いかがでしょうか。
        #byte value for iQ-R requires 2 byte data
        if self.plctype == const.iQR_SERIES:
            request_data += self._encode_value(value, mode="short")
        else:
            request_data += self._encode_value(value, mode="byte")

**Comment by senrust** [comment]
chamiso様

この度はご協力頂いたにもかかわらず, 私の不手際でお手数をおかけし申し訳ありません。

問題の原因は以下になります。
1. Pythonの型チェックを次バージョンで導入する作業を行っており、今回のアップデートにこの作業分をマージしてしまった。
2. そもそも型チェック導入バージョンに不具合があった。(そのためpymc3e.batchwrite_wordunitsで例外発生)
3. Pythonの型チェックのサポート上, 3.5以下を切り捨ててしまう結果になった。

そのため, バージョン0.2.7に対して、頂いた修正内容のみを適用したバージョンを0.2.9としてリリースしました。
読んでいる関数名が違いますが、動作としては同じです。
0.2.9はpythonバージョン3.0以上対応に戻しています。

型チェックは後日不具合修正を行いリリース予定です。
Python3.4, 3.5は申し訳ありませんが, すでにEOLとなっておりますので、
どこかのバージョンでインストールできなくなってしまうと思います。

この度は、本当にご協力ありがとうございます。
以上、どうぞよろしくお願いいたします。

**Comment by chamiso** [comment]
迅速な対応ありがとうございます。
iQ-R CPU、QCPUで確認しましたが、一通りのコマンドが正常に動作しました。
本パッケージには大きな可能性を感じており、ワクワクしております。

Pythonのバージョン問題については、仕方ないと思っています。
それでも0.2.9でPython 3.5をサポートいただけたことに大変感謝しております。

今後、こちらで旧バージョンのPythonを使いたい等になった場合は、
MITライセンスに従い、0.2.9をベースとして、こちらで個別パッチを作成・配布するなどさせてください。

この度は本当にありがとうございました。

**Comment by senrust** [comment]
chamiso様

この度はご協力誠にありがとうございます。
問題なく動作したようで良かったです。

もしよろしければchamiso様にpymcprotocolのCollaboratorに加わっていただければと思うのですが、
いかがでしょうか?
pymcprotocolへの追加機能等についてchamiso様のご意見&ご経験を頂ければ幸いと考えております。

Python3.5以下のサポート切り捨ては、
Python習熟のために型アノテーションを実装してみたいという程度の理由であり必須ではありません。
(プロジェクト作成時に書き殴ったひどいコードの整理はする必要があります...)

chamiso様に個別パッチを作成させてしまう手間を考えると、
chamiso様が直接pymcprotocolを編集できる方が手軽かなと思います。
Collaboratorならば, main以外のブランチで自由に作業できるように設定しています。
mainへのマージとPyPIへのリリースのみ、誠に勝手ですが私に行わせてください。

以上、ご検討のほどどうぞよろしくお願いします。

**Comment by chamiso** [comment]
senrust様

Collaboratorの件、承知いたしました。
GitHubはまだまだ不慣れですが、よろしくお願いいたします。

**Comment by senrust** [comment]
chamiso様

ご協力誠にありがとうございます。
もし追加機能がありましたらdevelopにpushしてmainへプルリクエストを作成して頂ければと思います。

以下pymcprotocolの環境です.

### 開発環境
poetryで開発を行っています。
```
pip install poetry
```
でインストール可能です.

### ブランチ構成
- master: 0.2.9のリリース内容です
- develop: typingブランチで実装していたリファクタリング内容を0.2.9に反映しました.
  冗長な記述を削減しているので多少はましな実装になっています。__現状未テストです__
- typing: 型アノテーションやリファクタリングをこちらで行っていました。
  型アノテーションの存在以外はdevelopと同じです。

### テスト環境
今回の0.2.8のリリース不具合の対策としてtestを書きました. 
```
poetry run pytest
```
でテストを実行できます。
お恥ずかしい限りですが、実装中のテスト機として使用していたQPLCがドナドナされてしまい,
現在は実機環境がありません。
__テストがそもそも正しいテストなのか? を確認する必要があります(本当に申し訳ありません)__

お手数ですが、developブランチでテストを実行し, テストが正しく記述されているか?
そして、developブランチに不具合がないかチェックしていただけないでしょうか?

重ね重ね申し訳ありません。
ご協力のほど、どうぞよろしくお願い申し上げます。

**Comment by chamiso** [comment]
ご連絡ありがとうございます。
Poetryに不慣れで申し訳ございません。poetry run pytestを行うためpoetry installを実行しようとしていますが、プロキシエラーが発生し、テストまでたどり着いていません。HTTPS_PROXYやHTTP_PROXYも設定してみましたが改善しません。社内のネットワークの問題かもしれません。そちらの環境ではプロキシサーバを使用していますでしょうか？

**Comment by senrust** [comment]
すみません。
プロキシ環境下を想定していませんでした。

poetryなしでもテストを行えるようにテストを書き換えました。
testsディレクトリ内で
```
python test_pymcprotocol.py
```
を実行すればpoetry環境がなくてもテスト関数を走らせられます。
接続先PLCのiPLCタイプ, ipアドレス,ポート番号については, testsディレクトリ内のconfig.iniを編集して頂ければと思います。

**Comment by chamiso** [comment]
testsディレクトリに移動するとconfig.iniの情報が取得できないようなので、1つ上のディレクトリで実行した結果を示します。
C:\Users\UserName\pymcprotocol-develop>python tests/test_pymcprotocol.py
Traceback (most recent call last):
  File "C:\Users\UserName\pymcprotocol-develop\tests\test_pymcprotocol.py", line 4, in <module>
    from src.pymcprotocol import Type3E
ModuleNotFoundError: No module named 'src'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\UserName\pymcprotocol-develop\tests\test_pymcprotocol.py", line 10, in <module>
    from src.pymcprotocol import Type3E
ModuleNotFoundError: No module named 'src'

テストプログラムからdevelopで作成されたpymcprotocolを利用できればよいのですが、うまくいかないようです。

**Comment by senrust** [comment]
developブランチを変更して
```
python tests/test_pymcprotocol.py
```
でもできるように修正いたしました。
これでだめな場合は, お手数ですがtestsディレクトリで実行した際のconfig.iniのインポートエラー内容を教えていただけないでしょうか?
(configiniでエラーということは、pymcprotocolのインポートには成功しているはずなので)

以上、どうぞよろしくお願いします。

**Comment by chamiso** [comment]
senrust様

一歩前進し、一部のテストコードが動作しました。
現在、以下のエラーが発生しています。

C:\Users\UserName\pymcprotocol-develop\tests>python test_pymcprotocol.py
Traceback (most recent call last):
  File "C:\Users\UserName\pymcprotocol-develop\tests\test_pymcprotocol.py", line 73, in <module>
    type3e_test(plctype, ip, port)
  File "C:\Users\UserName\pymcprotocol-develop\tests\test_pymcprotocol.py", line 51, in type3e_test
    assert 15 == value
AssertionError

C:\Users\UserName\pymcprotocol-develop\tests>python test_pymcprotocol.py
Traceback (most recent call last):
  File "C:\Users\UserName\pymcprotocol-develop\tests\test_pymcprotocol.py", line 73, in <module>
    type3e_test(plctype, ip, port)
  File "C:\Users\UserName\pymcprotocol-develop\tests\test_pymcprotocol.py", line 51, in type3e_test
    assert 15 == value
AssertionError

**Comment by senrust** [comment]
テストの実行に成功しよかったです。

すみません...
テストに不具合がありました...
developを更新しましたので、ご確認のほどお願いいたします。
おそらく、これでテストに成功するはずです。

大変お手数をおかけし申し訳ありません。

**Comment by chamiso** [comment]
senrust様
テストのご修正ありがとうございます。
QCPU,iQ-R CPUともに正常にテスト終了したようです。
よろしくお願いいたします。

**Comment by senrust** [comment]
chamiso様

テストが問題なく動き良かったです。
この度はお手数をおかけいたしました。
ご協力心より感謝申し上げます。

もし、追加機能のご要望や修正等ありましたら、遠慮なくお申し付けください。

以上、どうぞよろしくお願いいたします。
