### ISSUE TITLE
The program stops at socket timeout

### ISSUE THREAD

**Issue by junzz827** [senrust/pymcprotocol#5]
I always use it on Jetson.
Thanks for the very nice code.
I use the "While" statement to constantly monitor the D register of the PLC, 
but when the connection with the PLC is lost, the monitoring program on the Jetson side also stops at socket timeout.
When [self._is_connected] becomes False, I want to try to reconnect from Jetson side until the connection is possible.
I thought about adding return self._is_connected on line 126, but noticed that it stopped on line 123.
Do you have any good way? 

Junzz

**Comment by senrust** [comment]
Thank you for using pymcprotocol.
How about using try and exception block.
If connection is lost, pymcprotocol raises error.
You can catch and reconnect.

Senrust

**Comment by junzz827** [comment]
Thank you for your kindness!
I solved it by adding 'import socket' and 'except socket.timeout : ' .
I will do my best to aim for a production environment.

Junzz
