### ISSUE TITLE
Connection refused error

### ISSUE THREAD

**Issue by luckystar2794** [senrust/pymcprotocol#7]
Hi there,

I've encounter this error when I try to establish the connection " ConnectionRefusedError : [WinError 10061] no connection could be made because the target machine actively refused it "

Everything seems fine I'm able to ping the PLC Cpu

I'm using Mitsubishi Q13UDVCPU so its a type 3 based on the library description.

Could you advice me how I can resolve this? Thanks in advance

**Comment by senrust** [comment]
Thank you very much for using pymcprotocol.
Did you open a port for MC Protocol?
Best regards,

**Comment by luckystar2794** [comment]
Yes ive opened 
2 port
Tcp mcprotocol  2500
Udp mcprotcol  2501

Plc ip: 192.168.24.1
Pc ip: 192.168.24.188
Able to ping plc

**Comment by luckystar2794** [comment]
![Uploading 16427283135394611368764510739718.jpg…]()

As shown here
This is directly from existing running machine so there's other configuration in place hope its not confusing

**Comment by senrust** [comment]
Thanks for your check.
I cannot view your image...
Anyway, Can you try thins code?
And please share your enviroment (OS, Python Version).

```python
import socket

HOST = '192.168.24.1'  # The server's hostname or IP address
PORT = 2500
soc = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect((HOST, PORT))
```

**Comment by luckystar2794** [comment]
> Thanks for your check. I cannot view your image... Anyway, Can you try thins code? And please share your enviroment (OS, Python Version).
> 
> ```python
> import socket
> 
> HOST = '192.168.24.1'  # The server's hostname or IP address
> PORT = 2500
> soc = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
> s.connect((HOST, PORT))
> ```

Oh sorry about the image uploading as my network over here is bad.

I can understand what your code is attempting to do and I tried it before it couldnt work but could I check with you with your existing instruction

Pymc3e = pymcprotocol.Type3E()
..
Pymc3e.connect(Ip_addr, port)

Inside the library it has already been declared the socket type so I think the impact would be the same

Im using Windows 10, Pythob version 3.7.6

**Comment by senrust** [comment]
Ok. 
Did you reatart your PLC to reflect MC protocol settings?

**Comment by luckystar2794** [comment]
Yes I did and after that I tried reading it again and was able to see the changes

**Comment by senrust** [comment]
Ok.
Please test the above socket test.
I  have no idea why socket  connection refused.
Can you test from linux environment?

**Comment by luckystar2794** [comment]
Oh I dont have linux setup but thanks for responding to my issue. I will now close this issue since it could be my hardware related problem. Thanks again for your assistance
