### ISSUE TITLE
Connect issued: Socket.timeout error

### ISSUE THREAD

**Issue by chuanvan** [senrust/pymcprotocol#9]
Hi !

I used pymcprotocal to connect with melsec , i tryed test many time, but always have error: socket.timeout: timed out

Please help me bug it 
Thanks!

**Comment by senrust** [comment]
Thanks for using pymcprotocol.
Please assign IP adress and open mcprotocol port for your PLC.

Best regards,

**Comment by senrust** [comment]
Is your problem solved?
